import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

import { PrimeReactProvider, PrimeReactContext } from "primereact/api";
import { Toast } from "primereact/toast";
import { toastRef } from "@/libs/toastRef";
import ToastProvider from "@/context/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PrimeReactProvider>
          <ToastProvider />
          {/* <Toaster
            position="top-right"
            richColors
            expand={false}
            toastOptions={{
              classNames: {
                success: "bg-green-500 text-white border-green-600",
                error: "bg-red-500 text-white border-red-600",
                warning: "bg-orange-500 text-white border-orange-600",
                info: "bg-blue-500 text-white border-blue-600",
              },
            }}
          /> */}
          {children}
        </PrimeReactProvider>
      </body>
    </html>
  );
}
