"use client";
import { Sidebar } from "primereact/sidebar";
import { Button } from "primereact/button";
import { useState } from "react";

export default function DevTools({ debugQuery }) {
  const [visible, setVisible] = useState(false);

  return (
    <>
      {/* Floating Toggle Button */}
      <div className="fixed bottom-4 right-4 z-50">
        <Button
          icon="pi pi-code"
          rounded
          severity="help"
          aria-label="DevTools"
          onClick={() => setVisible(true)}
          tooltip="View Supabase Query"
          tooltipOptions={{ position: "left" }}
        />
      </div>

      <Sidebar
        visible={visible}
        position="right"
        onHide={() => setVisible(false)}
        className="w-full md:w-30rem bg-gray-900 text-white border-l border-gray-700"
        maskClassName="backdrop-blur-sm"
      >
        <div className="flex flex-col gap-4">
          <div className="border-b border-gray-700 pb-4">
            <h2 className="text-xl font-bold text-purple-400 mb-1">
              OpenRefer DevTools
            </h2>
            <p className="text-sm text-gray-400">
              Inspect the live Supabase query generated by the hook.
            </p>
          </div>

          {debugQuery ? (
            <div className="flex flex-col gap-4">
              {/* Status Block */}
              <div className="p-3 bg-gray-800 rounded border border-gray-700">
                <span className="text-xs font-bold text-gray-500 uppercase">
                  Target Table
                </span>
                <div className="text-lg text-green-400 font-mono">
                  public.{debugQuery.table}
                </div>
                <div className="text-xs text-gray-500 mt-1">
                  Last fetched: {debugQuery.timestamp}
                </div>
              </div>

              {/* Logic Block */}
              <div className="p-3 bg-gray-800 rounded border border-gray-700 font-mono text-sm">
                <span className="text-xs font-bold text-gray-500 uppercase block mb-2">
                  Active Filters (Where)
                </span>
                {debugQuery?.filters.length === 0 ? (
                  <span className="text-gray-500 italic">
                    No active filters
                  </span>
                ) : (
                  debugQuery?.filters.map((f, i) => (
                    <div key={i} className="mb-1">
                      <span className="text-blue-400">{f.field}</span>
                      <span className="text-pink-400 mx-2">{f.op}</span>
                      <span className="text-yellow-300">
                        &quot;{f.value}&quot;
                      </span>
                    </div>
                  ))
                )}
              </div>

              {/* Raw JSON Block */}
              <div className="p-3 bg-black rounded border border-gray-700 overflow-auto">
                <span className="text-xs font-bold text-gray-500 uppercase block mb-2">
                  Raw Hook State
                </span>
                <pre className="text-xs text-green-300 whitespace-pre-wrap">
                  {JSON.stringify(debugQuery, null, 2)}
                </pre>
              </div>
            </div>
          ) : (
            <div className="text-center text-gray-500 mt-10">
              Interact with the table to see query data.
            </div>
          )}
        </div>
      </Sidebar>
    </>
  );
}
